export const NAVIGATION_HIDE = 'NAVIGATION_HIDE';
export const NAVIGATION_SHOW = 'NAVIGATION_SHOW';
export const NAVIGATION_TOGGLE = 'NAVIGATION_TOGGLE';
export const SHOP_SET_CATEGORIES = 'SHOP_SET_CATEGORIES';
