//
// Alert
//
export const ALERT_PUSH = 'ALERT_PUSH';
export const ALERT_REMOVE = 'ALERT_REMOVE';

//
// Navigation
//
export const NAVIGATION_HIDE = 'NAVIGATION_HIDE';
export const NAVIGATION_SHOW = 'NAVIGATION_SHOW';
export const NAVIGATION_TOGGLE = 'NAVIGATION_TOGGLE';

//
// Shop
//
export const SHOP_CART_IS_EMPTY = 'SHOP_CART_IS_EMPTY';
export const SHOP_CART_ITEM_COUNT = 'SHOP_CART_ITEM_COUNT';
export const SHOP_CART_ITEM_REMOVED = 'SHOP_CART_ITEM_REMOVED';
export const SHOP_CART_SET_ITEM = 'SHOP_CART_SET_ITEM';
export const SHOP_CART_SUBTOTAL = 'SHOP_CART_SUBTOTAL';
export const SHOP_CART_TOTAL = 'SHOP_CART_TOTAL';
export const SHOP_INITIALIZE_CART = 'SHOP_INITIALIZE_CART';
export const SHOP_SET_CATEGORIES = 'SHOP_SET_CATEGORIES';

//
// Window
//
export const WINDOW_SET_MINIMIZED = 'WINDOW_SET_MINIMIZED';
export const WINDOW_SET_TITLE = 'WINDOW_SET_TITLE';
